apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_SERVICE_NAME
              value: demo-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.collectorEndpoint }}
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: none
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
