# Example using a self-signed cert with no cert manager
# Refer to https://opentelemetry.io/docs/platforms/kubernetes/helm/operator/ for different options
admissionWebhooks:
  certManager:
    enabled: false
  autoGenerateCert:
    enabled: true
    recreate: false
# Example using an existing cert manager
#  certManager:
#    issuerRef:
#      kind: Issuer
#      name: cert-manager-letsencrypt-production
